### ISSUE TITLE
selected row

### ISSUE THREAD

**Issue by emantzo** [DavidPatShuiFong/DTedit#10]
Hi again.
Is it possible to get the selected row, without using callbacks or action buttons in table?
Or is it possible to set up a selection callback (ie a callback activated when a row is selected)?
Thank you!

**Comment by DavidPatShuiFong** [comment]
You are welcome to test the latest commits in the develop branch! The currently selected row is returned in `results$rows_selected` (though only one row can be selected...)

**Comment by emantzo** [comment]
Sounds fantastic! Many thanks for the updated manuals, too!
