### ISSUE TITLE
Table width and column's width

### ISSUE THREAD

**Issue by aavanesy** [DavidPatShuiFong/DTedit#11]
I am working on a very large datatable with over 20 columns having very lengthy names.

For testing purposes let's use this

mtcars2 = cbind(mtcars, mtcars)
mtcars2 = cbind(mtcars, mtcars2)

When using this data in my DTedit, as result I obtain a table which is way out of the frame of my shiny app.
What I tried in datatable.options: scrollX, column widths, overall width
In shiny: using a div(style='600px') or column(6,) 
Even tried some CSS but I get a message that css will be ignored.

How can I control the size of this table so it stays within my screen?

Thank you

**Comment by DavidPatShuiFong** [comment]
This appears to work to me...

There is a scrollbar at the bottom of the table,
and the datatable 'resizes' according to available width.

```r
server <- function(input, output, session) {
    mtcars2 <- cbind(mtcars, mtcars)
    mtcars2 <- cbind(mtcars, mtcars2)
    wide_car_table <- dtedit(
        input, output,
        name = 'wide_car_list',
        thedata = mtcars2,
        datatable.options = list(scrollX = TRUE)
        
    )
    
}

ui <- shiny::fluidPage(
    shiny::h3('Wide Car Table'),
    shiny::uiOutput('wide_car_list')
)

shiny::shinyApp(ui = ui, server = server)
```

**Comment by emantzo** [comment]
I had the same problem, and I think a couple of DT options and extensions might be useful:

```
server <- function(input, output, session) {
  mtcars2 <- cbind(mtcars, mtcars)
  mtcars2 <- cbind(mtcars, mtcars2)
  wide_car_table <- dtedit(
    input, output,
    name = 'wide_car_list',
    thedata = mtcars2,
    datatable.options = list(scrollX = TRUE, dom = 'Bfrtip',
                             buttons = c('colvis')),
    
    datatable.call = function(...)
    {
      DT::datatable(..., extensions =c( 'Buttons','Responsive', "FixedColumns"), filter = "top")
    }
    
    
  )
  
}

ui <- shiny::fluidPage(
  shiny::h3('Wide Car Table'),
  shiny::uiOutput('wide_car_list')
)

shiny::shinyApp(ui = ui, server = server)
```

**Comment by aavanesy** [comment]
Thanks! both answers were very helpful.
