### ISSUE TITLE
Checkbox in row

### ISSUE THREAD

**Issue by emantzo** [DavidPatShuiFong/DTedit#12]
Hi again :)

I was wondering if it is possible to display checkboxes in the rows.

Thank you!

**Comment by DavidPatShuiFong** [comment]
within the row? As opposed to a checkbox inside the 'edit/update/new' dialog?

**Comment by emantzo** [comment]
I think having it within a row would be more convenient.
Is it already possible to have it the dialog box?

________________________________

**Comment by DavidPatShuiFong** [comment]
test code

```r
server <- function(input, output, session) {

      Grocery_List <- dtedit(
        input, output,
        name = 'Grocery_List',
        thedata = data.frame(
          Buy = c('Tea', 'Biscuits', 'Apples'),
          Quantity = c(7, 2, 5),
          stringsAsFactors = FALSE
        )
      )

      #### shinytest code for testing purposes only ########
      data_list <- list() # exported list for shinytest
      shiny::observeEvent(Grocery_List$thedata, {
        data_list[[length(data_list) + 1]] <<- Grocery_List$thedata
      })
      shiny::observeEvent(Grocery_List$rows_selected, ignoreNULL = FALSE, {
        data_list[[length(data_list) + 1]] <<-
          paste("Row selected: ", Grocery_List$rows_selected)
      }) # record the selected row
      shiny::exportTestValues(data_list = {data_list})
      ######################################################
    }

    ui <- shiny::fluidPage(
      shiny::h3('Grocery List'),
      shiny::uiOutput('Grocery_List')
    )

  shinyApp(ui = ui, server = server)
```

**Comment by DavidPatShuiFong** [comment]
Promising work by Matthias Hinz #cffb3f75578605ea3ce97ea05cbc9a85484e1c95

**Comment by DavidPatShuiFong** [comment]
Similar functionality now provided by accepted pull request #29, and related issue #19.

I decided not to actually include checkboxes *within* the displayed rows, as that would be inconsistent with the rest of the data editing interface, which modifies data using modals. I believe there are other R packages which provide 'in-row' editing!
