### ISSUE TITLE
Date Input displayed as numeric?

### ISSUE THREAD

**Issue by emantzo** [DavidPatShuiFong/DTedit#13]
Dear David,

I noticed that when I use dateInput, it is displayed in a numeric format, rather than date (I think the default is yyyy-mm-dd).

Many thanks for the consideration!

Here is one minimal example:

````
server <- function(input, output) {
  
  Grocery_List_Results <- dtedit(
    input, output,
    name = 'Grocery_List',
    thedata = data.frame(
      Buy = c('Tea', 'Biscuits', 'Apples'),
      Type = c('Plant', 'Processed', 'Fruit'),
      Quantity = c(7, 2, 5),
      day=c("2013-02-29","2014-02-29","2012-02-29"),
      stringsAsFactors = FALSE
    ),
    input.types = list(
      Buy = 'textInput',
      Type = 'selectInput',
      day="dateInput"
    ),
    input.choices = list(
      
      Type = c('Plant', 'Processed', 'Fruit', 'Animal')
    )
  )

  
}

ui <- fluidPage(
  h3('Grocery List'),
  uiOutput('Grocery_List'),
  
)

shinyApp(ui = ui, server = server)

**Comment by DavidPatShuiFong** [comment]
Yes, the date is shown as YYYY-MM-DD (perhaps that changes with locale...)

I think that is okay, myself ... what do you think it should look like?

![image](https://user-images.githubusercontent.com/8335820/91652149-8fd21700-ead7-11ea-9756-3818a1e4a725.png)

**Comment by emantzo** [comment]
When inserting the data in the dialog, yes it looks ok. 
But in the final table it is in a numeric form.
In the following table, the last row was added using today's date: 

![Screenshot 2020-08-30 20 25 12](https://user-images.githubusercontent.com/33861694/91665565-341b8400-eaff-11ea-9cd6-edae57f93d14.png)

Maybe it has sth to do with my settings?

Anyway, I managed to change it by messing around a little bit  with the dteditmod fun.

**Comment by DavidPatShuiFong** [comment]
Explicitly defining the `day` column as a `Date` type helps.

btw - some of the dates in the original example are invalid...

```r
server <- function(input, output) {
  
  Grocery_List_Results <- dtedit(
    input, output,
    name = 'Grocery_List',
    thedata = data.frame(
      Buy = c('Tea', 'Biscuits', 'Apples'),
      Type = c('Plant', 'Processed', 'Fruit'),
      Quantity = c(7, 2, 5),
      day=c(as.Date("2013-02-28"),as.Date("2014-02-28"),as.Date("2012-02-29")),
      stringsAsFactors = FALSE
    ),
    input.types = list(
      Buy = 'textInput',
      Type = 'selectInput',
      day="dateInput"
    ),
    input.choices = list(
      Type = c('Plant', 'Processed', 'Fruit', 'Animal')
    )
  )
}

ui <- fluidPage(
  h3('Grocery List'),
  uiOutput('Grocery_List'),
)

shinyApp(ui = ui, server = server)
```

**Comment by emantzo** [comment]
Right, this solves it! Many thanks!!
