### ISSUE TITLE
Getting following error when running this reactiveval example.

### ISSUE THREAD

**Issue by saketkanodia** [DavidPatShuiFong/DTedit#15]
Warning: Error in if: argument is of length zero
  51: dtedit
  50: server [#7]
Error in if (!is.data.frame(thedata) | ncol(thedata) < 1) { : 
  argument is of length zero

Can you help me fix?

**Comment by DavidPatShuiFong** [comment]
can you show a 'full' (but short) example?

**Comment by saketkanodia** [comment]
I am using the same example you have put on Github,

https://github.com/DavidPatShuiFong/DTedit/blob/master/inst/examples/reactivedataframe/app.R

**Comment by DavidPatShuiFong** [comment]
Hmmm, works for me.

When do you get the error, as soon as you enter that example?

What version of DTedit are you using : `packageVersion("DTedit")`?

When do you see the error?
* as soon as you try to press 'Enter' after `shinyapp(ui = ui, server = server)`?
* After you edit/add/delete a row?
* When you click the `Scramble an entry` button?

Regards, David

![image](https://user-images.githubusercontent.com/8335820/92587079-7cdef400-f2da-11ea-993e-5a49b5ba9308.png)

**Comment by saketkanodia** [comment]
Package Version is 1.0.0 and as soon as I hit shinyapp(ui = ui, server = server) , it gives the error. 

Even if I upgraded to 2.2.1 , it gave the same error.

![image](https://user-images.githubusercontent.com/6254944/92611208-2f608800-f2d6-11ea-83f8-0e0ec95aba7e.png)

**Comment by DavidPatShuiFong** [comment]
I'm pretty sure you are still using [`jbryer` DTedit version 1.0.0,](https://github.com/jbryer/DTedit/blob/master/R/dtedit.R) which at from line `116` of `dtedit.R` has

```r
	# Some basic parameter checking
	if(!is.data.frame(thedata) | ncol(thedata) < 1) {
		stop('Must provide a data frame with at least one column.')
	} else if(length(edit.cols) != length(edit.label.cols)) {
```

By contrast, [my branch version 2.2.1](https://github.com/DavidPatShuiFong/DTedit/blob/2.2.1/R/dtedit.R) (current version is 2.2.2 by the way) has, from line `322` of `dtedit.R`

```r
  # Some basic parameter checking
  if (!is.data.frame(thedataCopy) || ncol(thedataCopy) < 1) {
    stop("Must provide a data frame with at least one column.")
  } else if (length(edit.cols) != length(edit.label.cols)) {
```

If you have installed version `2.2.1` or `2.2.2`, re-start `R` and try again. If you are using Rstudio, click the 'Session' menu and choose the `Restart R' option.

However, there could be an additional problem. It looks like `thedata` is not defined by the time you call the `dtedit` function (jbryer version or my version). Can you show your actual call of the `dtedit` in the server function?
