### ISSUE TITLE
support for radioButtons and checkboxInput

### ISSUE THREAD

**Issue by splaisan** [DavidPatShuiFong/DTedit#19]
Could they (and possibly the other existing input controls) be added please, it would make the input forms much more rich than what they are now.

**Comment by DavidPatShuiFong** [comment]
Promising work by Matthias Hinz cffb3f7

Checkboxes appear in the dialog..

'FALSE/TRUE' appears in the column. The edit/add/copy modal dialog uses a checkbox

**Comment by splaisan** [comment]
cool, that will be nice to have

**Comment by MatthiasHinz** [comment]
Yes, I started working on it because the original DTedit threw an error when feeding a data.frame with a column of type logical.

I also I discovered that an unexpected fatal error is thrown when trying to edit a frame with just one single editable column. The following function call then produces bad output because `thedataCopy[, edit.cols]` coerces the input to an unnamed vector instead of keeping it as a data.frame.

[https://github.com/DavidPatShuiFong/DTedit/blob/7ce8de1b5fcd7195beee73ed4acce8ac33140ab7/R/dtedit.R#L365](https://github.com/DavidPatShuiFong/DTedit/blob/7ce8de1b5fcd7195beee73ed4acce8ac33140ab7/R/dtedit.R#L365)

Both issues seem to be solved on my fork and machine (linux/ubuntu). Maybe the tests need to be extended. Do you want a pull request?

## Example

``` R
library(shiny)
if (interactive()) {
  
  ui <- fluidPage(
    h3('Checkbox demo'),
    uiOutput('editor')
  )
  server <- function(input, output, session) {
    
    DTedit::dtedit(input, output,name = "editor", thedata = data.frame(letter=LETTERS[1:16],
      checkvalue=rep(c(TRUE,FALSE),8))
    )
  }
  shinyApp(ui, server)
} 
```

**Comment by splaisan** [comment]
great pick!
I discovered the existence of a problem recently and fixed the easy way by adding a field I do not really needed to the faulty tables.
Cool to see that it was a bug indeed.
Thanks

**Comment by DavidPatShuiFong** [comment]
Thanks @MatthiasHinz, a pull request for logical values will be kindly appreciated!

And thanks for fixing the single (editable) column bug!

I liberally scattered lines like ` thedataCopy[, view.cols, drop = FALSE]` to fix single-column problems in a far earlier iteration, but that one got away (or maybe crept right back in...).

A test extension *is* called for!

David

> Yes, I started working on it because the original DTedit threw an error when feeding a data.frame with a column of type logical.
> 
> I also I discovered that an unexpected fatal error is thrown when trying to edit a frame with just one single editable column. The following function call then produces bad output because `thedataCopy[, edit.cols]` coerces the input to an unnamed vector instead of keeping it as a data.frame.
> 
> https://github.com/DavidPatShuiFong/DTedit/blob/7ce8de1b5fcd7195beee73ed4acce8ac33140ab7/R/dtedit.R#L365
> 
> Both issues seem to be solved on my fork and machine (linux/ubuntu). Maybe the tests need to be extended. Do you want a pull request?

**Comment by DavidPatShuiFong** [comment]
@MatthiasHinz , would be pleased to see a pull request! otherwise, I was thinking of cherry-picking your nice commit, but would rather not...

> Yes, I started working on it because the original DTedit threw an error when feeding a data.frame with a column of type logical.
> 
> I also I discovered that an unexpected fatal error is thrown when trying to edit a frame with just one single editable column. The following function call then produces bad output because `thedataCopy[, edit.cols]` coerces the input to an unnamed vector instead of keeping it as a data.frame.
> 
> https://github.com/DavidPatShuiFong/DTedit/blob/7ce8de1b5fcd7195beee73ed4acce8ac33140ab7/R/dtedit.R#L365
> 
> Both issues seem to be solved on my fork and machine (linux/ubuntu). Maybe the tests need to be extended. Do you want a pull request?
> ## Example
> 
> ```r
> library(shiny)
> if (interactive()) {
>   
>   ui <- fluidPage(
>     h3('Checkbox demo'),
>     uiOutput('editor')
>   )
>   server <- function(input, output, session) {
>     
>     DTedit::dtedit(input, output,name = "editor", thedata = data.frame(letter=LETTERS[1:16],
>       checkvalue=rep(c(TRUE,FALSE),8))
>     )
>   }
>   shinyApp(ui, server)
> } 
> ```
