### ISSUE TITLE
is there a limit of the number of DTedit tables one can create

### ISSUE THREAD

**Issue by splaisan** [DavidPatShuiFong/DTedit#22]
Dear David,

I have a very weird issue where my first 3 DTedit tables (out of about 10) do work but adding/editing or deleting from the 4th upwards triggers the same error which is not clear to me

```
Warning: Error in if: missing value where TRUE/FALSE needed
  72: observeEventHandler
   1: runApp
```

I looked very close and all the code blocks are copy paste of each other then editing the variables and names. I am stuck.

Thanks for any hint

**Comment by aavanesy** [comment]
I have an app with about 10 DTedits, works just fine.

**Comment by splaisan** [comment]
thanks @aavanesy for our feedback, I must have typos in my code, hard to find them as the error is not very verbose.

**Comment by DavidPatShuiFong** [comment]
thanks @aavanesy for the confirmation, too!

`DTedit::dteditmod_demo()` has four DTedit tables.

> I have an app with about 10 DTedits, works just fine.

**Comment by splaisan** [comment]
apologies for having doubted, it was a stupid typo of mine, where a data.frame had become a vector and was not feeding well the DTedit object. Case closed :-)

I really enjoy the package although still have difficulties managing related fields in insert and edit callbacks

**Comment by DavidPatShuiFong** [comment]
> apologies for having doubted, it was a stupid typo of mine, where a data.frame had become a vector and was not feeding well the DTedit object. Case closed :-)
> 
> I really enjoy the package although still have difficulties managing related fields in insert and edit callbacks

No worries. `DTedit` is very much my secondary project (to support a much more substantial project, which is also not my 'day job'). But I appreciate the feedback, and you pointed out what is definitely a bug in another issue!

**Comment by splaisan** [comment]
possibly my problem was related to https://github.com/DavidPatShuiFong/DTedit/issues/19#issuecomment-715328453
