### ISSUE TITLE
DTedit inside reactive environment triggers edit more than once

### ISSUE THREAD

**Issue by aavanesy** [DavidPatShuiFong/DTedit#28]
See the simple app below

```
library(shiny)
library(DT)
library(DTedit)

ui <- fluidPage(
  column(4,
         br(),
         br(),
         selectInput('cols','columns', multiple = T,
                     selected = names(mtcars)[1],
                     choices = names(mtcars)
                     ),
         uiOutput('dt1')
  )
)

server <- function(input, output) {
  
  observeEvent(input$cols,{
    dt1 <- dtedit(input, output,
                  name = 'dt1',
                  thedata = mtcars,
                  view.cols = input$cols
                  )
  })


}

shinyApp(ui = ui, server = server, options = list(launch.browser=TRUE))
```

Dynamic selection works just fine.

Whenever I select  5+ column and I click on edit on a row I observe "blinking"

So I went to see what happens inside the code

```
 observeEvent(input[[paste0(name, "_edit")]], {
        row <- input[[paste0(name, "dt_rows_selected")]]
        if (!is.null(row) && row > 0) {
            shiny::showModal(editModal(row))
            inputEvent_handles <<- inputEvent_object$new("_edit")
        }
    })
```

And I realized this is being triggered more than once even if I press edit once.
I suppose because of the column additions and reactivity is somehow considers as in this has been clicked for many tables at once.

**Comment by DavidPatShuiFong** [comment]
Thanks Arkadi for this observation.

I rather suspect that several 'observeEvent's for the `_edit` button are being created, each time `dtedit` is called, which is each time `input$cols` triggers the `observeEvent` in your example.

Unfortunately, the 'previous' dtedit's observeEvents might not actually be disposed of/garbage-collected each time 'dtedit' is called.

**Comment by ablooky** [comment]
Hello 
Have you found a solution? I am experiencing the same issue.

**Comment by DavidPatShuiFong** [comment]
> Hello
> Have you found a solution? I am experiencing the same issue.

Thanks ablooky.

I think the code ...

```r
observeEvent(input$cols,{
    dt1 <- dtedit(input, output,
                  name = 'dt1',
                  thedata = mtcars,
                  view.cols = input$cols
                  )
  })
```

creates multiple instances of the `dtedit` object, without actually destroying the previous object (including all the associated HTML/JS observers created when the datatable object is created).

`dtedit` doesn't destroy previous instances of the `dtedit` table when it is called again.

Is the recreation of `dtedit` instances also happening in your code, @ablooky ?

Apparently it *is* possible to destroy previous datatables instances:

1. https://datatables.net/reference/event/destroy
2. https://stackoverflow.com/questions/54272640/is-it-possible-to-clear-the-displayed-output-in-shinyapp-using-actionbutton

I tried to destroy previous `dtedit` instances before without success in the past. But maybe I should try again (unless you do it first, @ablooky !)

David

**Comment by ablooky** [comment]
I was able to fix my issue. Turns out putting my code  dtedit(...) in a renderUI code block caused the issue. 

```
output$ivmbm_params<-renderUI({
    ivmbm_test_systems_results<-DTedit::dtedit(input, output,
                                               name = 'ivmbm_test_systems_params2',
                                               thedata = ivmbm_user_test_systems,
                                               show.copy=F,show.delete = FALSE,show.insert=F,
                                               datatable.options = list(dom = 't'))
conditions<-list(uiOutput('ivmbm_test_systems_params2'))
})
```
By removing credit from renderUI, the issue was resolved. 
```
    ivmbm_test_systems_results<-DTedit::dtedit(input, output,
                                               name = 'ivmbm_test_systems_params2',
                                               thedata = ivmbm_user_test_systems,
                                               show.copy=F,show.delete = FALSE,show.insert=F,
                                               datatable.options = list(dom = 't'))
output$ivmbm_params<-renderUI({
conditions<-list(uiOutput('ivmbm_test_systems_params2'))
})
```

**Comment by DavidPatShuiFong** [comment]
Yes, that makes sense. By removing the `dtedit` from the reactive, you avoid creating multiple instances of the `dtedit` object.
