### ISSUE TITLE
The `data` argument for the call back functions is passed with `NA` values converted to empty character strings

### ISSUE THREAD

**Issue by andresrcs** [DavidPatShuiFong/DTedit#33]
When an update or insert is performed the returning `data` is passed with `NA` values converted to empty character strings (i.e. ""), this is an unintuitive behavior and has consequences when constructing SQL queries using `glue::glue_sql()` since empty character strings don't get converted to SQL `NULL`

This is a small reprex to illustrate the problem

```
library(shiny)
library(DTedit)

ui <- fluidPage(
           uiOutput('table'),
           h3(textOutput("text")),
        )


server <- function(input, output) {
    value <- reactiveVal(NA_character_)
    
    sample_data <- data.frame( stringsAsFactors = FALSE,
        col = c("test"),
        value = c(NA_character_)
    )
    
    update_callback <- function(data, olddata, row) {
        value(data[row,]$value)
        return(data)
    }
    
    datatable <- dtedit(input, output,
                        name = 'table',
                        thedata = sample_data,
                        view.cols = names(sample_data),
                        edit.cols = names(sample_data),
                        show.delete = FALSE,
                        show.insert = FALSE,
                        show.copy = FALSE,
                        callback.update = update_callback
    )
    
    output$text <- renderText({
        paste("Is NA?:", is.na(value()))
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by DavidPatShuiFong** [comment]
Thanks @andresrcs , including for the example code!

Unfortunately, I don't think `shiny::textInput`, which is what `dtedit` uses for character strings, can be set to `NA`, as shown in the slightly modified example below.

Which means that `data` will always contain an empty character string rather than `NA`.

However, `olddata` contains the original `NA` (as can be seen when examining `olddata` using the `browser()` break).

It is also possible to identify the empty character situation in the callback, and 'manually' adjust `data`, as in the example below.

```r
library(shiny)
library(DTedit)

ui <- fluidPage(
    uiOutput('table'),
    h3(textOutput("text")),
    h3(textOutput("text2")),
    shiny::textInput("alpha", "Alpha", value = NA_character_)
)


server <- function(input, output) {
    value <- reactiveVal(NA_character_)
    
    sample_data <- data.frame( stringsAsFactors = FALSE,
                               col = c("test"),
                               value = c(NA_character_)
    )
    
    update_callback <- function(data, olddata, row) {
        browser()
        if (data[row,]$value == "") {
            data[row,]$value <- NA_character_
        }
        value(data[row,]$value)
        return(data)
    }
    
    datatable <- dtedit(input, output,
                        name = 'table',
                        thedata = sample_data,
                        view.cols = names(sample_data),
                        edit.cols = names(sample_data),
                        show.delete = FALSE,
                        show.insert = FALSE,
                        show.copy = FALSE,
                        callback.update = update_callback
    )
    
    output$text <- renderText({
        paste("Is NA?:", is.na(value()))
    })
    
    output$text2<- renderText({
        paste("Is Alpha NA?:", is.na(input$alpha))
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by andresrcs** [comment]
Yes, of course we can manually check `data` in the callback function, but my point was that getting an empty string instead of `NA` is an unexpected behavior in general so I thought that data consistency should be checked by the package and not manually by the user.
If you didn't have the knowledge of how your package internally work, would you intuitively expect `NA` to be converted to empty strings?, I know `textInput()` behaves that way but since the user doesn't create it manually, at least for me this wasn't expected. Maybe you could consider adding a warning in the documentation at least.

Anyways, thanks for your time checking on this.

**Comment by DavidPatShuiFong** [comment]
Thanks, I think it would be quite difficult for me to 'guess' the intent of a `DTedit` user in this circumstance.

So I've chosen to add the warning in the documentation.
