### ISSUE TITLE
How to install the release branch of dtedit?

### ISSUE THREAD

**Issue by emantzo** [DavidPatShuiFong/DTedit#6]
Please excuse my potentially naive question:

I would like to try the release branch of DTedit, and so I tried to install the release branch 2.2.1, of `DavidPatShuiFong/DTedit' , as suggested.

However, it gave this error:
`> devtools::install_github('DavidPatShuiFong/DTedit@2.2.2')
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref 2.2.2`

Playing around, I tried and managed to install the 2.2.0 branch.
Now also the [RPub vignette](https://rpubs.com/DavidFong/DTedit) works fine(was not working with the "official" DTedit package).

Is this indeed the right release to use?

On another issue (request, rather): Are you planning to allow for DTedit to save the data on gsheets?
In my opinion, it would be of great use, in order to collect data across collaborators.

Many thanks for your time, and congratulations on your  significant work!

**Comment by DavidPatShuiFong** [comment]
First, my apologies, the `2.2.1` tag was  not properly attached to this repository! Though as you found out, `2.2.0` was properly tagged.

I've just tested:

```r
devtools::install_github('DavidPatShuiFong/DTedit@2.2.1')
```
...and it works. (there is no `2.2.2`!)

Development has been on Windows, mostly,

The vignette was written by myself, and assumed the use of `DTedit` in this repository, not the 'official' repository. I think that all code written for the 'official' `DTedit` *should* work, although I have fixed some bugs in the original `1.0.0` code. Jason Bryer, the original author and creator has contacted me, however, and we plan to chat about merging the code I (and others) have written to the 'official' repository. Hopefully we will then do a CRAN submission.

As for Google Sheet integration, `2.0.0` of `DTedit` can both react to changes in the original dataframe, and also (of course) inform the calling functions if a user edits the dataframe. Google sheet integration appears to be a big undertaking, I notice there are projects https://googlesheets4.tidyverse.org/ and  (soon to be obsolete) https://github.com/jennybc/googlesheets 

If googlesheet integration works without those packages, then I think a program using `DTedit` can then 'save' the data to google sheets through means of those packages.

**Comment by emantzo** [comment]
Dear David,

I am grateful for your reply and hints!

I take the opportunity, to ask another thing, maybe trivial but indispensable to me (I am 4 days old in shiny).
Is there some example showing how to access the edited –via dtedit- dataframe and then save it (without using the default buttons of the ui)?
This  would help me greatly to save it to a gsheet.
I have been struggling with this for hours, but to no avail.

Many thanks for your kind help!

**Comment by emantzo** [comment]
Dear David,

Please do not bother with my previous post (issue is closed anyway, as I just noticed).
I finally managed to make it work ☺
Many thanks for your time!

From: Eirin Mantzouni
Sent: Monday, August 3, 2020 7:20 AM
To: DavidPatShuiFong/DTedit <reply@reply.github.com>
Subject: RE: [DavidPatShuiFong/DTedit] How to install the release branch of dtedit? (#6)

Dear David,

I am grateful for your reply and hints!

I take the opportunity, to ask another thing, maybe trivial but indispensable to me (I am 4 days old in shiny).
Is there some example showing how to access the edited –via dtedit- dataframe and then save it (without using the default buttons of the ui)?
This  would help me greatly to save it to a gsheet.
I have been struggling with this for hours, but to no avail.

Many thanks for your kind help!

**Comment by DavidPatShuiFong** [comment]
Glad to hear you got things working.

I assume that something like this - from the [vignette](https://rpubs.com/DavidFong/DTedit) - works:

```r
server <- function(input, output) {

  Grocery_List_Results <- dtedit(
    input, output,
    name = 'Grocery_List',
    thedata = data.frame(
      Buy = c('Tea', 'Biscuits', 'Apples'),
      Quantity = c(7, 2, 5),
      stringsAsFactors = FALSE
    )
  )

  observeEvent(Grocery_List_Results$thedata, {
    message(Grocery_List_Results$thedata)
  })

}

ui <- fluidPage(
  h3('Grocery List'),
  uiOutput('Grocery_List')
)

shinyApp(ui = ui, server = server)
```

Appreciate your compliments!

> Dear David, Please do not bother with my previous post (issue is closed anyway, as I just noticed). I finally managed to make it work ☺ Many thanks for your time! 
>> Is there some example showing how to access the edited –via dtedit- dataframe and then save it (without using the default buttons of the ui)?

**Comment by emantzo** [comment]
Yes, it was simple as that! Grateful for your time and prompt help. Στις 3 Αυγ 2020 22:59, ο χρήστης David Fong <notifications@github.com> έγραψε:

Glad to hear you got things working.

I assume that something like this - from the vignette - works:

server <- function(input, output) {



  Grocery_List_Results <- dtedit(

    input, output,

    name = 'Grocery_List',

    thedata = data.frame(

      Buy = c('Tea', 'Biscuits', 'Apples'),

      Quantity = c(7, 2, 5),

      stringsAsFactors = FALSE

    )

  )



  observeEvent(Grocery_List_Results$thedata, {

    message(Grocery_List_Results$thedata)

  })



}



ui <- fluidPage(

  h3('Grocery List'),

  uiOutput('Grocery_List')

)



shinyApp(ui = ui, server = server)

Appreciate your compliments!



Dear David, Please do not bother with my previous post (issue is closed anyway, as I just noticed). I finally managed to make it work ☺ Many thanks for your time!



Is there some example showing how to access the edited –via dtedit- dataframe and then save it (without using the default buttons of the ui)?
