### ISSUE TITLE
Support for POSIXct column types

### ISSUE THREAD

**Issue by emilmahler** [DavidPatShuiFong/DTedit#7]
Hi David. Thanks for your great improvements to the DTedit package.

The standard version of DT for R/Shiny supports date formats like POSIXct, but I get the error:
`Error in switch(class(x), list = "selectInputMultiple", character = "textInput",  : 
  EXPR must be a length 1 vector`

Reproduce the bug with:
```
library(shiny)
# devtools::install_github('DavidPatShuiFong/DTedit@2.2.1')
library(DTedit)

server = function(input, output, session) {
  reactive_data <- reactive({
    # Would normally be a database connection
    data.frame(time = Sys.time())
  })
  
  subcomponents_dt <- dtedit(
    input, output,
    name = 'myDT',
    thedata = reactive_data #although this is a reactive variable, no need for ()
  )
}

ui <- fluidPage(
  uiOutput('myDT')
)

shinyApp(ui, server)
```

**Comment by DavidPatShuiFong** [comment]
Thanks, I see the problem, `class(Sys.time())` returns `[1] "POSIXct" "POSIXt"`.

`class()` doesn't like that two-element vector!

Furthermore, there is no current code in `dtedit` (either the original `1.0.0` version or the current `2.2.1` to handle date-times.

**Comment by DavidPatShuiFong** [comment]
Now in the `develop` branch, can be installed with `devtools::install_github("DavidPatShuiFong/dtedit@develop")`

```r
library(shiny)
# devtools::install_github('DavidPatShuiFong/DTedit@2.2.1')
library(DTedit)

server = function(input, output, session) {
  reactive_data <- reactive({
    # Would normally be a database connection
    data.frame(time1 = Sys.time(), date2 = Sys.Date())
  })

  subcomponents_dt <- dtedit(
    input, output,
    name = 'myDT',
    useairDatepicker = TRUE,
    thedata = reactive_data #although this is a reactive variable, no need for ()
  )
}

ui <- fluidPage(
  uiOutput('myDT')
)

shinyApp(ui, server)
```

'Time' input requires using the `airDatepickerInput` from `shinyWidgets`. There is a new option, `useairDatepicker` to support using time inputs. I don't particularly like the `airDatepickerinput` very much, I can't seem to 'type' in the date or time in the way that can be done with `shiny::dateInput`

Let me know what you think...

**Comment by emilmahler** [comment]
This is excellent - many thanks for your help. It works great!
