### ISSUE TITLE
Future request: min max for numericInput and Date

### ISSUE THREAD

**Issue by emantzo** [DavidPatShuiFong/DTedit#9]
Dear David,

just a thought, as a user of this powerful package, I would find it very helpful if dtedit would allow for min and max arguements, referring to numerInput and DateInput input.types.
Thank you for your consideration.

**Comment by DavidPatShuiFong** [comment]
The more I think about it, the worse it gets.

Since in applications that *I* can think of, the minimum/maximum allowed values are likely to be dynamic, changing according to circumstance. Better handled from within the callback (which can comfortably handle dynamic changes to allowed input range, without resorting to even more reactives).

I'm closing this issue for now.

**Comment by emantzo** [comment]
I  hate to insist on it, and I am not insistging, but I would just like to eplain how it may be useful.

Well, I am using an attributes table, stating the basic options for each column (name, input.type, editable, visible, choices for selectInput). I use this table as an input to a script which then dynamically builds the Dtedit table. Thus, it would be useful for me to be able to define the min and max for the numericInput vars.
But probably it is ust me, so there is no need to bother.
Thank you for your time!

________________________________

**Comment by DavidPatShuiFong** [comment]
This is possible - in a fashion - with the `shinyFeedback` package. I have testing code in issue #17 . Currently a preliminary commit (only for new entries, currently).

I don't think `shinyFeedback` isn't designed to *prevent* wrong inputs. But who knows, with the `inputId`, maybe you can change the contents of the widget...

**Comment by emantzo** [comment]
A quick question, and please excuse me if already answered:
Is it possible to use the shinyFeedpack to display warnings in the New or Edit windows, above the widgets, before the data input?

**Comment by DavidPatShuiFong** [comment]
> A quick question, and please excuse me if already answered:
> Is it possible to use the shinyFeedback to display warnings in the New or Edit windows, above the widgets, before the data input?

the 'feedback' section shinyFeedback shows the feedback 'warnings', or otherwise, right next to the input widget, before the data is input. The 'feedback' can be changed (e.g. change text and/or colour) depending on the value of the widget.

shinyFeedback package also contains a 'toaster' function, which is the *only* shiny toaster which seems to work with shiny modals (the 'edit/new' popup window).

**Comment by emantzo** [comment]
At some point I had tried to mess with the dtedit function and managed to display the allowed min and max vals below the numericInput widgets (it still gives me errors some times, though). Let me know if you have the time/ interest to have a look.

**Comment by DavidPatShuiFong** [comment]
> At some point I had tried to mess with the dtedit function and managed to display the allowed min and max vals below the numericInput widgets (it still gives me errors some times, though). Let me know if you have the time/ interest to have a look.

Actually, the ability to use `shinyFeedback` is already available in the 'develop' branch. Look at the example code in the vignette (https://rpubs.com/DavidFong/DTedit) under 'inputEvent'. The vignette only shows 'warning' code, but it is possible to create 'success' code too (all of which can show the suggested parameters). Note that the feedback needs to be 'hidden/cleared' if you wish to show a different/new feedback.

An example in 'production' code is in https://github.com/DavidPatShuiFong/DailyMeasure/blob/develop/R/module_Configuration_server.R lines 277-352. Ignore the comments about module namespaces (this is referring to an earlier problem I had with trying to retrieve the widget values from the ID within a module environment).

**Comment by DavidPatShuiFong** [comment]
![image](https://user-images.githubusercontent.com/8335820/97801488-35009b80-1c91-11eb-8b40-54d838117bf5.png)

```r
library(shiny)
library(DTedit)

server <- function(input, output) {
  
  Grocery_List_Results <- dtedit(
    input, output,
    name = 'Grocery_List',
    thedata = data.frame(
      Buy = c('Tea', 'Biscuits', 'Apples'),
      Quantity = c(7, 2, 5),
      stringsAsFactors = FALSE
    ),
    numeric.width = 300,
    inputEvent = list(
      Quantity = function(x, value) {
        # x will be the inputID of the 'Quantity' widget
        # value will be the contents of the input widget
        #
        # if *not* called as a module, then value == input[[x]]
        # however, if 'dteditmod' is called, then value != input[[x]] because
        # 'x' does *not* include the ID 'prefix' of the module. (the module's
        # ID prefix could be added 'manually' by the function, potentially).
        # Strangely, the inputId parameter of shinyFeedback can use 'x'
        # without any modification, even if 'dteditmod' is called.
        
        # if the input box is empty, value will be NA
        if (!is.na(value) && value < 0) {
          shinyFeedback::hideFeedback()
          shinyFeedback::showFeedbackWarning(
            inputId = x,
            text = "Less than zero"
          )
        } else {
          shinyFeedback::hideFeedback(x)
          shinyFeedback::showFeedbackSuccess(
            inputId = x,
            text = "Recommend between zero and ten inclusive"
          )
        }
        if (!is.na(value) && value > 10 && value <= 100) {
          shinyFeedback::showToast("success", "That's a lot!")
        }
        if (!is.na(value) && value > 100) {
          shinyFeedback::showToast("error", "Too many, try again!")
          shiny::updateNumericInput(
            session = shiny::getDefaultReactiveDomain(),
            inputId = x,
            value = NA
          )
        }
      },
      Buy = function(x, value) {
        if (value == "") {
          shinyFeedback::showFeedbackDanger(
            inputId = x,
            text = "Name must not be empty!"
            # note that this is just a warning, really
            # since this feedback itself does not
            # enforce the warning.
          )
        } else {
          shinyFeedback::hideFeedback(x)
        }
      }
    )
  )
  
}

ui <- fluidPage(
  shinyFeedback::useShinyFeedback(),
  h3('Grocery List'),
  uiOutput('Grocery_List')
)

shinyApp(ui = ui, server = server)
```

**Comment by emantzo** [comment]
Wow nice!
My approach was simply to add a helptext below the widgets, and the string arguments were passed as a vector to the dtedit fun.

**Comment by DavidPatShuiFong** [comment]
okay, glad that seems suitable. closing the issue for now!
